### ISSUE TITLE
Fix warning "No handlers could be found for logger "ctk_cli.module""

### ISSUE THREAD

**Issue by jcfr** [cdeepakroy/slicer_cli_web_plugin#3]
```
$ docker run  girder/slicer_cli_web_plugin sample_python_cli --help
No handlers could be found for logger "ctk_cli.module"
usage: sample_python_cli.py [-h] [-V] [--xml] [--returnparameterfile <file>]
                            [--boolean1 <boolean>] [--boolean2 <boolean>]
                            [--boolean3 <boolean>] [-d <double>]
                            [--directory1 <directory>]
                            [-e {Ron,Eric,Bill,Ross,Steve,Will}]
                            [-f <float-vector>] [--file1 <file>]
                            [--files <file>] [-i <integer>] [--image1 <image>]
                            [--image2 <image>]
                            [--string_vector <string-vector>]
                            arg0 arg1
[...]
```

**Comment by MayeulChassagnard** [comment]
As suggested by Deepak, we should handle the issue before `Applications/sample_python_cli/sample_python_cli.py` (ref https://github.com/cdeepakroy/slicer_cli_web_plugin/pull/7/commits/bd9c4daf03f69c3d6bb7bf769ca6bc7eef99633f).

Indeed, we should remove the error when we parse it [here](https://github.com/girder/girder/blob/master/plugins/item_tasks/server/cli_parser.py#L51).

**Comment by jcfr** [comment]
Well done.

@MayeulChassagnard Can you confirm the issue is solved and close the issue ? Thanks

**Comment by MayeulChassagnard** [comment]
I do not have authorizations on the repository (we need @cdeepakroy to close it) but I do confirm that the issue is fixed.

**Comment by jcfr** [comment]
Great. Thanks :+1:
